apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-pipeline
  template:
    metadata:
      labels:
        app: app-pipeline
    spec:
      containers:
        - name: app-pipeline
          image: hamzabaker/app-pipeline:1.0.0-17
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
