apiVersion: v1
kind: Service
metadata:
  name: app-pipeline
  labels:
    app: app-pipeline
spec:
  selector:
    app: app-pipeline

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
